language: node_js
sudo: false
node_js:
  - "0.10"
script:
  - npm run lint
env:
  - TEST_BROWSER=firefox
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6 # upgrade libstdc++ on linux to support C++11k
